Common/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from Common.views import RegisterView

app_name = 'Common'

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    url(r'^reset_password/$', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
        success_url=reverse_lazy('Common:password_reset_done'),
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'^reset_password/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('Common:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

]

Project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from Shop.views import MainPageView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Common.urls')),
    url(r'^', include('Shop.urls')),
    url(r'^', MainPageView.as_view(), name='main'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.conf.urls import url
from django_filters.views import FilterView

from Shop.filters import ProductFilter
from Shop.views import ProductsListView, ProductInfoView, AddProductView, EditProductView, DeleteProductView, \
    cart_add, cart_remove, cart_detail, CreateOrderView

app_name = 'Shop'

urlpatterns = [
    url(r'^products/$', ProductsListView.as_view(), name='products_list'),
    url(r'^product/(?P<product_id>[0-9]+)/$', ProductInfoView.as_view(), name='product_info'),
    url(r'^search/$', FilterView.as_view(filterset_class=ProductFilter,
                                         template_name='products/search_product.html', ordering='name'), name='search'),
    url(r'^add_product/$', AddProductView.as_view(), name='add_product'),
    url(r'^edit_product/(?P<pk>[0-9]+)/$', EditProductView.as_view(), name='edit_product'),
    url(r'^delete_product/(?P<pk>[0-9]+)/$', DeleteProductView.as_view(), name='delete_product'),

    url(r'^cart/$', cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>[0-9]+)/$', cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>[0-9]+)/$', cart_remove, name='cart_remove'),
    url(r'^order/$', CreateOrderView.as_view(), name='order'),

]

templates/accounts/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
       <form method="POST">
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Log In</legend>
               {{ form|crispy }}
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-info" type="submit">Login</button>
               <smal class="text-muted ml-2">
                   <a href="{% url 'Common:password_reset' %}">Forgot Password?</a>
               </smal>
           </div>
       </form>
{% endblock content %}

templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
   <h2>You have been logged out</h2>
   <div class="border-top pt-3">
       <small class="text-muted">
           <a href="{% url 'login' %}">Log in Again</a>
       </small>
   </div>
{% endblock content %}

templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
   <div class="content-section">
       <form method="POST">
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Reset Password</legend>
               {{ form|crispy }}
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-info" type="submit">Request Password reset</button>
           </div>
       </form>
   </div>
{% endblock content %}

templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h5>Your new password has been successfully set. Now you can access your account using your new password.</h5>
    <a href="{% url 'Common:login' %}">Log in</a>.
{% endblock %}

templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% block content %}
  {% if validlink %}
    <h3>Set New Password</h3>
    <form method="post">
    {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Set Password</button>
     </form>
  {% else %}
    <p>The password reset link expired.</p>
  {% endif %}
{% endblock %}

templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
   <div class="content-section">
       <form method="POST">
           {% csrf_token %}
           <fieldset class="form-group">
            <h10>Your password has been reset. Please check your mail for further instructions.</h10>
           </fieldset>
       </form>
   </div>
{% endblock content %}

templates/accounts/password_reset_email.html
{% autoescape off %}

You're receiving this email because you requested a password reset for your user account at EverythingShop.

Please go to the following page and set a new password:

{{ protocol }}://{{ domain }}{% url 'Common:password_reset_confirm' uidb64=uid token=token %}

Your username: {{ user.get_username }}

Regards,
EverythingShop

{% endautoescape %}

templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="login">
        <center>
        <h2>Create account</h2>
             {% if messages %}
                {% for message in messages %}
                <font color="red">{{ message }}</font>
                {% endfor %}
             {% endif %}
         <form method="post" >
             {% csrf_token %}
             <table>
                {{ form|crispy }}
             </table>
             <input type="submit" name="submit" value="Register" />
         </form>
        </center>
     </div>
{% endblock %}