Common/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from Common.views import RegisterView

app_name = 'Common'

urlpatterns = [
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),

    url(r'^reset_password/$', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html',
        success_url=reverse_lazy('Common:password_reset_done'),
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='accounts/password_reset_subject.txt'),
        name='password_reset'),

    url(r'^reset_password/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),

    url(r'^reset_password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('Common:password_reset_complete')), name='password_reset_confirm'),

    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),

]

Project/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from Shop.views import MainPageView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Common.urls')),
    url(r'^', include('Shop.urls')),
    url(r'^', MainPageView.as_view(), name='main'),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Shop/urls.py
from django.conf.urls import url
from django_filters.views import FilterView

from Shop.filters import ProductFilter
from Shop.views import ProductsListView, ProductInfoView, AddProductView, EditProductView, DeleteProductView, \
    cart_add, cart_remove, cart_detail, CreateOrderView

app_name = 'Shop'

urlpatterns = [
    url(r'^products/$', ProductsListView.as_view(), name='products_list'),
    url(r'^product/(?P<product_id>[0-9]+)/$', ProductInfoView.as_view(), name='product_info'),
    url(r'^search/$', FilterView.as_view(filterset_class=ProductFilter,
                                         template_name='products/search_product.html', ordering='name'), name='search'),
    url(r'^add_product/$', AddProductView.as_view(), name='add_product'),
    url(r'^edit_product/(?P<pk>[0-9]+)/$', EditProductView.as_view(), name='edit_product'),
    url(r'^delete_product/(?P<pk>[0-9]+)/$', DeleteProductView.as_view(), name='delete_product'),

    url(r'^cart/$', cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>[0-9]+)/$', cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>[0-9]+)/$', cart_remove, name='cart_remove'),
    url(r'^order/$', CreateOrderView.as_view(), name='order'),

]

templates/add_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{#   <div class="content-section">#}
       <form method="POST" enctype="multipart/form-data" >
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Add new product</legend>
               {{ form|crispy }}
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-info" type="submit">Add</button>
           </div>
       </form>
{% endblock content %}

templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
<title>Everything Shop</title>
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>EverythingShop</title>
</head>
<body>
   <header class="site-header">
     <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
       <div class="container">
       {% if request.user.is_authenticated %}
        <h20 class="nav-item nav-link">Logged as: {{ user.first_name }}</h20>
       {% endif %}
         <a class="navbar-brand mr-4" href="{% url 'main' %}">Shop</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarToggle">
           <div class="navbar-nav mr-auto">
               {% if user.is_authenticated %}
                <li class="active"><a class="nav-item nav-link" href="{% url 'main' %}">Home</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Shop:products_list' %}">Product list</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Shop:search' %}">Search for product</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Shop:add_product' %}">Add new product</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Shop:cart_detail' %}">Your shopping cart</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Common:password_reset' %}">Password Reset</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Common:logout' %}">Logout</a></li>
               {% else %}
                <li class="active"><a class="nav-item nav-link" href="{% url 'main' %}">Home</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Shop:products_list' %}">Product list</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Shop:search' %}">Search for product</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Common:login' %}">Login</a></li>
                <li><a class="nav-item nav-link" href="{% url 'Common:register' %}">Register</a></li>
               {% endif %}
           </div>
         </div>
       </div>
     </nav>
   </header>

<div id="body"><br>
{% if user.is_authenticated %}
    <h10><strong>Logged as: {{ user.first_name }} {{ user.last_name }}</strong></h10>
{% endif %}
<br>
<p>
 {% if messages %}
{% for message in messages %}
<font color="red">{{ message }}</font>
{% endfor %}
{% endif %}
</p>

<br>
<br>
    {% block content %}

    {% endblock content %}

  <div class="banner">&nbsp;</div>

<div id="footer">
  <div id="footnote">
    <div class="section">Copyright &copy; 2012 <a href="#">Company Name</a> All rights reserved | Website Template By <a target="_blank" href="http://www.freewebsitetemplates.com/">freewebsitetemplates.com</a></div>
  </div>
</div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/cart_detail.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

    <center><h1>Your shopping cart</h1></center>
    <table class="table table-bordered">

    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>

    <tbody>

        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        {% if product.image %}
                        <img src="{{ product.image.url }}"/>
                        {% else %}
                        <img width="60" height="60" src="/static/noimage.jpg">
                        {% endif %}
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>
                <form action="{% url 'Shop:cart_add' product.id %}" method="post">
                    {% csrf_token %}
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.update }}
                    <input type="submit" value="Update">
                </form>
                </td>
                <td><a href="{% url 'Shop:cart_remove' product.id %}">Remove</a> </td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="4"></td>
            <td>{{ cart.get_total_price }}</td>
        </tr>
    </tbody>
    </table>

    <p align="center">
        <button class="btn btn-outline-info" type="submit"><a href="{% url 'Shop:products_list' %}" class="button">Continue shopping</a></button>
        <br><br>
        <button class="btn btn-outline-info" type="submit"><a href="{% url 'Shop:order' %}" class="button">Order</a></button>
    </p>

{% endblock content %}

templates/change_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
   <div class="content-section">
       <form method="POST" enctype="multipart/form-data" >
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Change product details</legend>
               {{ form|crispy }}
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-info" type="submit">Save changes</button>
           </div>
       </form>
{% endblock content %}

templates/confirmation_email.html
{% autoescape off %}
Hi {{ user.first_name }} {{ user.last_name }},

We are pleased to confirm your order placed in our shop. Thank you and have a nice day.
Please check your invoice attached.

Regards,
http://{{ domain }}

{% endautoescape %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

{% endblock content %}

templates/invoice.html
<html>
    <body>
    <center>
        <div class='wrapper'>
            <div class='header'>
                <p class='title'>Invoice {{ order }} </p>
            </div>
        </div>
        <div class='details'>
            Bill to: {{ first_name }} {{ last_name }} <br>
            Amount: {{ total_price }} <br/>
            Date: {{ date }} <br>
            Payment deadline: {{ deadline }}
            <hr class='hrItem' />
        </div>
    </center>
    <table class="table table-bordered">

    <thead>
      <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Unit price</th>
        <th><strong>Price</strong></th>
      </tr>
    </thead>
    <tbody>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>{{ product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="2"></td>
            <td><strong>{{ cart.get_total_price }}</strong></td>
        </tr>
    </tbody>
    </table>
    <br>
    <center>
    <h5>Payment data:</h5>
    {% for i, j in seller.items %}
    <p>{{ i }} : {{ j }}</p>
    {% endfor %}
    </center>
    </body>
</html>

templates/order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
     <center><h1>Your order details</h1></center>
    <table class="table table-bordered">

    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>

    <tbody>

        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>
                    <a href="{{ product.get_absolute_url }}">
                        {% if product.image %}
                        <img src="{{ product.image.url }}"/>
                        {% else %}
                        <p>No image</p>
                        {% endif %}
                    </a>
                </td>
                <td>{{ product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.total_price }}</td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr>
            <td>Total</td>
            <td colspan="3"></td>
            <td>{{ cart.get_total_price }}</td>
        </tr>
    </tbody>
    </table>
   <div class="content-section">
       <form method="POST" enctype="multipart/form-data" >
           {% csrf_token %}
           <fieldset class="form-group">
               {{ form|crispy }}
           </fieldset>
           <div class="form-group">
               <center><button class="btn btn-outline-info" type="submit">Confirm order</button></center>
           </div>
       </form>

{% endblock content %}

templates/order_created.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <center>
    <h1>Thank you for buying in our shop.</h1>
    <p>Your order has been completed. Your order number is <strong>{{ order.id }}</strong></p>
    <p>Please check your email to see the invoice attached</p>
    </center>
{% endblock content %}

templates/product_confirm_delete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <center>
       <form method="POST" >
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Are you sure to delete product {{ product.name }} ?</legend>
           </fieldset>
           <div class="form-group">
               <button class="btn btn-outline-info" type="submit">Yes, delete this product.</button>
               <a href="{% url 'Shop:products_list' %}">--> No, take me back to products list.</a>
           </div>
       </form>
    </center>
{% endblock content %}

templates/product_info.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <center>
<h2>Product: {{ product.name }}</h2>
    <p>Producer: {{ product.producer }}</p><br>
    <p>Price: {{ product.price }}</p><br>
    {% if product.image %}
        <img width="300" height="300" src="{{ product.image.url }}">
    {% endif %}
    <article class="media content-section">
        <div class="media-body">
         <h5>Description:</h5>
            <p>{{ product.description }}</p><br>
        </div>
    </article>
        <form action="{% url 'Shop:cart_add' product.id %}" method="post">
        {% csrf_token %}
        {{ cart_product_form }} <br>
        <input type="submit" value="Add to cart">
    </form>
    <br>
        <button class="btn btn-outline-info" type="submit"><a href="{% url 'Shop:products_list' %}">Back to products list</a></button>
    </center>
{% endblock content %}

templates/product_list.html
{% extends "base.html" %}
{% load imagekit %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content %}
        <form action="#" method="GET" id="form_page" onsubmit="return check_change()">
    {%if paginator %}
        {% include "pagination.html" %}
    {% endif %}
</form>
    <center>


  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Producer</th>
        <th>Price</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
    {% for product in products %}
        <tr>
        {% if product.image %}
            <td><img width="60" height="60" src="{{ product.image.url }}"></td>
{#            <td><img src="{{ product.image_thumbnail.url }}"/></td>#}
{#            <td>{% thumbnail '100x50' product.image_thumbnail %}</td>#}
{#            <td>{% generateimage 'Shop:thumbnail' source=product.image_thumbnail %}</td>#}
            {% else %}
            <td><img width="60" height="60" src="/static/noimage.jpg"></td>
            {% endif %}
          <td><a href="{% url 'Shop:product_info' product.id %}">{{ product.name }}</a></td>
          <td>{{ product.producer }}</td>
          <td>{{ product.price }}</td>
            <td><a href="{% url 'Shop:edit_product' product.id %}">Edit</a></td>
            <td><a href="{% url 'Shop:delete_product' product.id %}">Delete</a></td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No data</td>
        </tr>
       {% endfor %}

    </tbody>
  </table>
    </center>
    <form action="#" method="GET" id="form_page" onsubmit="return check_change()">
    {%if paginator %}
        {% include "pagination.html" %}
    {% endif %}
</form>
{% endblock content %}

templates/search_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block content %}
</form>
<form method="get">
    <div class="well">
      <h4 style="margin-top: 0">Filter by:</h4>
      <div class="row">
        <div class="form-group col-sm-4 col-md-3">
            <h8>Product name</h8>
          {{ filter.form.username.label_tag }}
          {% render_field filter.form.name class="form-control" %}
        </div>
        <div class="form-group col-sm-4 col-md-3">
            <h8>Producer</h8>
          {{ filter.form.first_name.label_tag }}
          {% render_field filter.form.producer class="form-control" %}
        </div>
            {% for choice in filter.form.groups %}
              <label class="checkbox-inline">
                {{ choice.tag }} {{ choice.choice_label }}
              </label>
            {% endfor %}
          </div>
        </div>
      </div>
      <button type="submit" class="btn btn-primary">
        <span class="glyphicon glyphicon-search"></span> Search
      </button>
    </div>
  </form>
  <table class="table table-bordered">
    <thead>
      <tr>
          <th>Image</th>
        <th>Product</th>
        <th>Producer</th>
        <th>Price</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for product in filter.qs %}

        <tr>
                {% if product.image %}
            <td><img width="60" height="60" src="{{ product.image.url }}"></td>
{#            <td><img src="{{ product.image_thumbnail.url }}"/></td>#}
{#            <td>{% thumbnail '100x50' product.image_thumbnail %}</td>#}
{#            <td>{% generateimage 'Shop:thumbnail' source=product.image_thumbnail %}</td>#}
            {% else %}
            <td><img width="60" height="60" src="/static/noimage.jpg"></td>
            {% endif %}
          <td><a href="{% url 'Shop:product_info' product.id %}">{{ product.name }}</a></td>
          <td>{{ product.producer }}</td>
            <td>{{ product.price }}</td>
            <td><a href="{% url 'Shop:edit_product' product.id %}">Edit</a></td>
            <td><a href="{% url 'Shop:delete_product' product.id %}">Delete</a></td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="5">No data</td>
        </tr>

      {% endfor %}

    </tbody>
  </table>
{% endblock %}